version: '3.3'

volumes:
  data:

services:  

  myadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:      
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    volumes:
      - /sessions
    networks:
      - app-networks

  db:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./data/db:/var/lib/mysql"
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - app-networks

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-networks

  mail:
    image: bytemark/smtp
    container_name: mail
    restart: always
    networks:
      - app-networks

  app:
    build: .
    container_name: ${NAME_APP_WEB}
    ports:
      - "8000:80"
      - "3000:443"
    restart: always
    depends_on:
      - db
      - redis
      - mail
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./setup.sh:/usr/share/nginx/setup.sh"
      - "./src:/usr/share/nginx"
      - "./etc/ssl:/etc/ssl"      
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
